---
output: 
  md_document:
    variant: markdown_github
---

## Transparencias del trabajo en equipo de la asignatura "Big Data"

<!-- El párrafo de abajo has de dejarlo tal cual. NO HAS DE CAMBIAR NADA!!-->

Repo utilizado para elaborar las transparencias del trabajo en equipo para la asignatura "Programación y manejo de datos en la era del Big Data" de la Universitat de València durante el curso 2021-2022. La página web de la asignatura puede verse aquí: <https://perezp44.github.io/intro-ds-20-21-web/>.

<!-- En la linea de abajo TIENES QUE SUSTITUIR "perezp44" por tu usuario de Github-->

La versión final de estas transparencias puede visualizarse en: <https://alejandrocp00.github.io/_trabajo_BigData_slides/>.


<!-- En la linea de abajo TIENES QUE SUSTITUIR (otra vez) "perezp44" por tu usuario de Github-->

La versión final del trabajo puede visualizarse en: <https://alejandrocp00.github.io/_trabajo_BigData_equipo/>.



<!-- Abajo podéis escribir lo que queráis, igual un resumen del trabajo, o ..., o ... pero al menos, tenéis que poner el título del trabajo y el nombre de los componentes del equipo-->

El título del trabajo es  Análisis de criptomonedas, evolución y actualidad.  En el trabajo analizamos la evolución de las principales criptomonedas a lo largo de los últimos años y estudiamos sus principales peligros de cara al futuro, como la volatilidad o la especulación.
Además, trataremos de representar su presencia en el mundo y cómo realizar un análisis técnico del precio del Bitcoin y Ethereum

<!-- Finalmente, acuérdate que cuando hayas hecho los cambios y hayas dejado este archivo como hayáis decidido, TENEIS que knittearlo para que los cambios se actualicen en el fichero Readme.md, que es el que finalmente se visualizará en Github-->


